### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by denisbetsi** [chaudum/spring-data-crate-example#1]
FAILURE: Build failed with an exception.
- What went wrong:
  Could not resolve all dependencies for configuration ':compile'.
  > Could not find :spring-data-crate-1.0.0.BUILD-SNAPSHOT:.
  Searched in the following locations:

Looks like spring-data-create is missing. Found a project 
https://github.com/KPTechnologyLab/spring-data-crate

Which I think this is trying to reference. Not 100% sure though. That one also fails to build as per instructions.  Is there spring-data-crate-1.0.0.BUILD-SNAPSHOT.jar kicking around somewhere ?

**Comment by chaudum** [comment]
hi @denisbetsi 
you'll need to compile the `spring-data-crate` jar first because it is not available on maven or bintray.
there's a blog post how to create the example app using `crate-spring-data`: https://crate.io/a/using-sprint-data-crate-with-your-java-rest-application/

**Comment by denisbetsi** [comment]
Looks like that library in the example isn't compatible with latest version of CRATE. It fails tests during compilation.

**Comment by chaudum** [comment]
@denisbetsi we'll take a look!

**Comment by denisbetsi** [comment]
I've opened an issue with person who created that library. Looks like he made one adjustment to it to make the delete function. 
[https://github.com/KPTechnologyLab/spring-data-crate/issues/2#issuecomment-191067618](url)

Now, only thing remains is all tests with byComplexId are failing. It's unable to cast the complex ID into string. Not sure if that is a Crate feature or not.

**Comment by chaudum** [comment]
hi @denisbetsi 

seems like the creator of the spring-data-crate adaptor already opened an issue for that: https://github.com/crate/crate/issues/3320

we'll have a look :)

**Comment by denisbetsi** [comment]
Awesome, thank you!
